name: rspec

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        railties:
          - '7.0'
          - '7.1'
          - '7.2'
    env:
      BUNDLE_GEMFILE: gemfiles/railties${{ matrix.railties }}.gemfile

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rspec
      continue-on-error: ${{ matrix.allow_failures == 'true' }}
